### ISSUE TITLE
Combine market and peer in the same process

### ISSUE THREAD

**Issue by shuaimu** [sbu-416-24sp/orcanet-rust#6]
It seems the market and peer can only run separately, they need to be combined in the same process.

**Comment by reaovyd** [comment]
I don't mind this and our team provides a library crate for integration to do so, but what's the point of having gRPC methods/a protobuf file for the market server then?

Also, if we're doing this, then I believe it would be useful to also get rid of using an http server to transfer the file chunks and we can further use [libp2p's websocket](https://docs.rs/libp2p-websocket/latest/libp2p_websocket/). I haven't exactly dug deep into this part here, but I think using libp2p's protocols to have peers behind NATs/firewalls communicate and then easily using libp2p's websockets to transfer file chunks would be better than us setting up an http server and trying to implement our own version of solving the problem of peers behind NATs/firewalls.

As per the library crate, it's feature complete for users as we provide a struct that has [Peer::register_file, Peer::check_holders](https://github.com/reaovyd/orcanet-market-rust/blob/main/market_dht/src/peer.rs), but not exactly yet done for dealing with peers behind NAT/firewall problems and we're in the middle of refactoring due to incorporating the protocols to solve the problem of peers behind NATs/firewalls.

**Comment by shuaimu** [comment]
I don't follow. the gRPC server is for communication between peers. What is it related to this discussion?

**Comment by reaovyd** [comment]
@shuaimu The market server currently uses the protobuf file made [here](https://github.com/sbu-416-24sp/orcanet-market-go/blob/bf868f32e12b43a68e09846aa978a1ed902e6a7b/market/market.proto). In doing so, we have tonic and the protobuf compilers to codegen the gRPC server and client functionality where the gRPC functionality provides two of the methods we want: `check_holders` and `register_file`. The market server currently uses the code generated gRPC server functionality to setup the `check_holders` and `register_file` methods. The peer node team uses the code generated gRPC client functionality to call those two methods since the point of the market server (as per the system design) is to learn about the suppliers for a specific filehash; thus, gRPC, based on the previously mentioned protobuf file, only really serves as an IPC mechanism between the market server and the peer node as the market server runs its own gRPC server for these two methods and listens on some port for the client requests coming from the peer node.

Any actual communication between peers is done through the libp2p library in which a market server team would be using to setup p2p communications (which is based on the libp2p protobuf file specs and is probably using some kind of rpc generated functionalities if that's what you're referring to)

I think based on the original issue you want to combine the peer and market into a single process meaning we can get rid of the gRPC server if it only serves as an IPC mechanism between the peer node team's implementation and the market server.

**Comment by shuaimu** [comment]
I see. Interesting points. So the peer-market communication can be simple function calls? Then we should definitely do this (combine the two processes).

**Comment by reaovyd** [comment]
The only other issue I see with just combining two processes together would be just losing the interoperability if say a Golang peer node team wanted to communicate with a Rust gRPC market server, but for the most part, I agree with that and our team does provide a library crate where it requires changing no more than a few lines (I believe if no errors come with using our library); we mention this in the Google chats for the Rust teams. Our library crate is enough for a PoC with nodes within the same local network, and I believe (even without the relay protocol specifically) it should work if there is at least one publicly dialable node (opened its own peer port for the machine it's running on) and this is typically the set of boot nodes we'll have, which will be relay servers. The issue we're solving at the moment in our library is for actually getting rid of needing that public node/relay server (at the very least, a bit later on in a node's lifecycle) if two nodes can ["hole punch"](https://docs.libp2p.io/concepts/nat/hole-punching/) each other's firewalls/NATs, which would allow two peers to directly connect (of course after they're done using the relay server). We're currently in the stage of a refactor of the library to support peers communicating behind a NAT/firewall.

Then, a potential next step to this would be then getting rid of http and using libp2p's websockets (for transferring file chunks) since the tradeoff of coming up with a solution to the NAT problem ourselves (without libp2p) might be even larger for development time.

**Comment by reaovyd** [comment]
We can still provide the capabilities to implement a gRPC market server and support interoperability still (but would just require someone implementing a gRPC market server using the library). So, the library is modular in the sense that a user like the peer node team can just link to the library natively or can still be incorporated into a gRPC market server and all it'll do is serve as a distributed database (which is the main requirement anyways) and allow a peer implementation from another language to communicate with a Rust implementation of the market server (since all they need is a gRPC generated client from the protobuf file).
